container:
    image: python:3.5-slim

code_check_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install pylint requests yapf
    pip_install_script: pip install pylint requests yapf
    utils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd utils
        - ./devutils/run_utils_pylint.py --hide-fixme
    devutils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd devutils
        - ./devutils/run_devutils_pylint.py --hide-fixme

validate_config_task:
    validate_config_script: ./devutils/validate_config.py

validate_patches_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install requests
    pip_install_script: pip install requests
    chromium_download_cache:
        folder: chromium_download_cache
        fingerprint_script: cat chromium_version.txt
        populate_script: mkdir chromium_download_cache && ./utils/downloads.py retrieve -i downloads.ini -c chromium_download_cache
    validate_patches_script:
        - tar -xf chromium_download_cache/chromium-$(cat chromium_version.txt).tar.xz
        - ./devutils/validate_patches.py -l chromium-$(cat chromium_version.txt)

# vim: set expandtab shiftwidth=4 softtabstop=4:
