container:
    dockerfile: .cirrus_Dockerfile

code_check_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install pylint requests yapf
    pip_install_script: pip install pylint requests yapf
    utils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd utils
        - ./devutils/run_utils_pylint.py --hide-fixme
    devutils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd devutils
        - ./devutils/run_devutils_pylint.py --hide-fixme

validate_config_task:
    validate_config_script: ./devutils/validate_config.py

validate_patches_task:
    chromium_download_cache:
        folder: chromium_download_cache
        fingerprint_script: cat chromium_version.txt
        populate_script:
            - mkdir chromium_download_cache
            - ./utils/downloads.py retrieve -i downloads.ini -c chromium_download_cache
    validate_patches_script:
        - ./utils/downloads.py unpack -i downloads.ini -c chromium_download_cache chromium_src
        - ./devutils/validate_patches.py -l chromium_src || true

# vim: set expandtab shiftwidth=4 softtabstop=4:
