container:
    dockerfile: .cirrus_Dockerfile

code_check_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install pylint requests yapf
    pip_install_script: pip install pylint requests yapf
    utils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd utils
        - ./devutils/run_utils_pylint.py --hide-fixme
    devutils_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd devutils
        - ./devutils/run_devutils_pylint.py --hide-fixme

validate_config_task:
    validate_config_script: ./devutils/validate_config.py

validate_with_source_task:
    chromium_download_cache:
        folder: chromium_download_cache
        fingerprint_script: cat chromium_version.txt
        populate_script:
            - mkdir chromium_download_cache
            - ./utils/downloads.py retrieve -i downloads.ini -c chromium_download_cache
    unpack_source_script:
        - ./utils/downloads.py unpack -i downloads.ini -c chromium_download_cache chromium_src
    validate_patches_script:
        - ./devutils/validate_patches.py -l chromium_src
    validate_lists_script:
        - ./devutils/update_lists.py --pruning pruning.list.new --domain-substitution domain_substitution.list.new -t chromium_src
        - diff -U 0 --label "domain_substitution.list (in git)" --label "domain_substitution.list (computed)" domain_substitution.list domain_substitution.list.new
        - diff -U 0 --label "pruning.list (in git)" --label "pruning.list (computed)" pruning.list pruning.list.new

# vim: set expandtab shiftwidth=4 softtabstop=4:
